name: Release from branch (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 0.0.0-branch-test)"
        required: true
        default: "0.0.0-branch-test"

jobs:
  release:
    uses: doda2025-team20/build-tools/.github/workflows/docker-build-and-push.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image: ghcr.io/doda2025-team20/model-service-sandbox
      context: .
      dockerfile: ./Dockerfile
      platforms: linux/amd64,linux/arm64
      version: ${{ inputs.version }}
      add_latest: false
    secrets: inherit
